#!/bin/bash
# 增强版公众号采集主脚本
# 集成采集、同步、PR工作流、通知

set -e

WECHAT_DIR="/home/codespace/clawd/wechat-collector"
REPO_DIR="/workspaces/MyMoltbot"
LOG_DIR="$WECHAT_DIR/logs"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_DIR/enhanced_workflow.log"
}

log "🚀 启动增强版公众号采集流程"

# 1. 运行增强版采集
log "📱 步骤1: 采集公众号产品..."
cd "$WECHAT_DIR"
python3 enhanced_collector.py >> "$LOG_DIR/enhanced_collector.log" 2>&1

# 2. 检查是否有新数据
NEW_DATA=$(find "$WECHAT_DIR/data" -name "wechat_products_*.json" -mtime -0.5 2>/dev/null | wc -l)

if [ "$NEW_DATA" = "0" ]; then
    log "⏭️ 没有新的数据文件"
else
    log "📦 发现 $NEW_DATA 个新数据文件"

    # 3. 同步到产品库
    log "🔄 步骤2: 同步到产品库..."
    cp "$WECHAT_DIR/data"/wechat_products_*.json "$REPO_DIR/obsidian-templates/产品库/公众号数据/"

    # 4. 创建分支和PR
    log "🔗 步骤3: 创建 Pull Request..."
    cd "$REPO_DIR"

    BRANCH_NAME="wechat-enhanced-$(date '+%Y%m%d')"
    git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

    git add -A
    git commit -m "📱 增强版公众号产品更新 - $(date '+%Y-%m-%d')

- 增强关键词监控
- 新增监控账号（武汉信贷联盟、贷款中介联盟等）
- 自动变化检测
- 智能产品信息提取

Generated by Enhanced WeChat Collector" 2>/dev/null || log "⏭️ 暂无变更"

    git push -u origin "$BRANCH_NAME" 2>/dev/null || log "⏭️ 推送失败"

    log "✅ 分支已创建: $BRANCH_NAME"
    echo ""
    echo "🔗 PR链接: https://github.com/jiangzhuizzz/MyMoltbot/pull/new/$BRANCH_NAME"
fi

# 5. 发送通知
log "📤 步骤4: 发送通知..."
cd "$WECHAT_DIR"
python3 notify-user.py "collection_complete" "$NEW_DATA" >> "$LOG_DIR/notify.log" 2>&1 || log "⚠️ 通知失败"

log ""
log "✅ 增强版采集流程完成！"
log ""
log "📊 执行摘要:"
log "  - 监控公众号: 14个"
log "  - 新增数据: $NEW_DATA 个文件"
log "  - 变化检测: 开启"
log "  - 自动同步: 开启"

echo ""
echo "💡 手动运行:"
echo "  - 采集: python3 $WECHAT_DIR/enhanced_collector.py"
echo "  - 查看日志: tail -f $LOG_DIR/enhanced_collector.log"
