#!/bin/bash
# 武汉贷款公众号产品采集主脚本
# 整合采集、PR工作流、通知

set -e

WECHAT_DIR="/home/codespace/clawd/wechat-collector"
REPO_DIR="/workspaces/MyMoltbot"
LOG_DIR="$WECHAT_DIR/logs"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_DIR/main.log"
}

log "🚀 启动武汉贷款公众号产品采集流程"

# 1. 采集产品数据
log "📱 步骤1: 采集公众号产品..."
cd "$WECHAT_DIR"
python3 collector.py >> "$LOG_DIR/collector.log" 2>&1
log "✅ 数据采集完成"

# 2. 同步到产品库
log "🔄 步骤2: 同步到产品库..."
cd "$REPO_DIR"

# 检查是否有新数据
NEW_DATA=$(find "$WECHAT_DIR/data" -name "wechat_products_*.json" -mtime -1 2>/dev/null | wc -l)

if [ "$NEW_DATA" = "0" ]; then
    log "⏭️ 没有新的数据需要同步"
else
    log "📦 发现 $NEW_DATA 个新数据文件"
    
    # 创建分支
    BRANCH_NAME="wechat-update-$(date '+%Y%m%d')"
    git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
    
    # 复制新数据
    cp "$WECHAT_DIR/data"/wechat_products_*.json "obsidian-templates/产品库/公众号数据/"
    
    # 提交
    git add -A
    git commit -m "📱 公众号产品更新 - $(date '+%Y-%m-%d')

- 新增武汉贷款公众号产品数据
- 数据来源：武汉贷款通、汉口贷款助手等

Generated by WeChat Collector" 2>/dev/null || log "⏭️ 暂无变更"
    
    # 推送到远程
    git push -u origin "$BRANCH_NAME" 2>/dev/null || log "⏭️ 推送失败或无需推送"
    
    log "✅ 数据已同步，分支: $BRANCH_NAME"
fi

# 3. 生成报告
log "📊 步骤3: 生成采集报告..."
cd "$WECHAT_DIR"
python3 collector.py > /dev/null 2>&1
REPORT_FILE=$(find "$WECHAT_DIR/data" -name "report_*.md" -mtime -1 | tail -1)
if [ -n "$REPORT_FILE" ]; then
    log "📄 报告: $REPORT_FILE"
fi

# 4. 发送通知
log "📤 步骤4: 发送通知..."
cd "$WECHAT_DIR"
python3 notify-user.py "collection_complete" "$NEW_DATA" >> "$LOG_DIR/notify.log" 2>&1 || log "⚠️ 通知失败"

log ""
log "✅ 采集流程完成！"
log ""
log "📋 执行摘要:"
log "  - 采集公众号: 10个"
log "  - 新增数据: $NEW_DATA 个文件"
log "  - 分支: wechat-update-$(date '+%Y%m%d')"

echo ""
echo "💡 下次运行: 明天同一时间"
echo "📁 数据目录: $WECHAT_DIR/data"
