#!/bin/bash
# 产品数据更新 Git 工作流
# 自动创建 PR 供审核

set -e

REPO_DIR="/workspaces/MyMoltbot"
BRANCH_PREFIX="product-update"
TODAY=$(date '+%Y%m%d')
WORK_DIR="/home/codespace/clawd/product-collector"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "🚀 启动产品更新 Git 工作流"

cd "$REPO_DIR"

# 检查是否有新文件
NEW_FILES=$(find "$REPO_DIR/obsidian-templates/产品库" -name "*.new.md" 2>/dev/null | wc -l)

if [ "$NEW_FILES" = "0" ]; then
    log "⏭️ 没有新的产品文件需要更新"
    exit 0
fi

log "📦 发现 $NEW_FILES 个新文件待处理"

# 创建分支
BRANCH_NAME="${BRANCH_PREFIX}-${TODAY}-$(date '+%H%M%S')"
log "🌿 创建分支: $BRANCH_NAME"

git checkout -b "$BRANCH_NAME"

# 移动新文件到正确位置
for file in $(find "$REPO_DIR/obsidian-templates/产品库" -name "*.new.md"); do
    NEW_NAME=$(echo "$file" | sed 's/\.new\.md$/.md/')
    mv "$file" "$NEW_NAME"
    git add "$NEW_NAME"
    log "✅ 处理文件: $NEW_NAME"
done

# 提交更改
git add -A
git commit -m "📦 产品数据更新 - $(date '+%Y-%m-%d')

- 更新产品利率信息
- 新增产品描述
- 数据来源：银行官网、贷款资讯网站

Generated by Clawdbot"

# 推送到远程
log "📤 推送到远程..."
git push -u origin "$BRANCH_NAME"

# 创建 PR
log "🔗 创建 Pull Request..."

PR_BODY=$(cat << EOF
## 📦 产品数据更新

### 更新内容

- 更新了以下产品的信息：
$ (git diff --name-only HEAD~1 HEAD | sed 's/^/- /')

### 数据来源

- 银行官网
- 贷款资讯网站（融360等）
- 微信公众号

### 检查清单

- [ ] 利率信息是否准确
- [ ] 申请条件是否完整
- [ ] 产品标签是否合适
- [ ] 佣金比例是否正确

### 说明

此 PR 由自动系统生成，请仔细审核后合并。

---

_由 Clawdbot 自动生成_
EOF
)

# 使用 gh CLI 创建 PR（如果可用）
if command -v gh &> /dev/null; then
    gh pr create \
        --title "📦 产品数据更新 - $(date '+%Y-%m-%d')" \
        --body "$PR_BODY" \
        --base main \
        --head "$BRANCH_NAME"
    
    log "✅ PR 创建成功！"
    echo ""
    echo "请访问 GitHub 审核并合并 PR"
else
    log "⚠️ gh CLI 未安装，跳过 PR 创建"
    log "💡 分支 $BRANCH_NAME 已推送，请手动创建 PR"
fi

log "✅ Git 工作流完成！"

# 通知用户（在下一部分实现）
echo "$BRANCH_NAME" > "$WORK_DIR/last-pr-branch.txt"
